name: ramp-mobility

dependencies:
  - python=3.7
  - spyder
  - numpy>=1.10
  - matplotlib>=1.5.1
  - pandas>= 0.24.0
  - pip
  - pip:
    - convertdate
    - https://github.com/dr-prodigy/python-holidays/tarball/master
 